#!/usr/bin/env bash

# `-e` (errexit): a real failure (broken symlink collision, a missing source
# dir, a bad copy) now aborts with a non-zero exit instead of printing
# "Done." anyway. Every place a non-zero exit is *expected* (existence
# probes, optional cleanups, `git config` on an unset key) is localized with
# `|| true`, an `if`, or a `&&`/`||` list — see the comments below.
set -Eeuo pipefail

# Resolve the repo root from the script's own location so the installer works
# no matter which directory it is invoked from.
DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COLOR_GRAY="\033[1;38;5;243m"
COLOR_BLUE="\033[1;34m"
COLOR_GREEN="\033[1;32m"
COLOR_RED="\033[1;31m"
COLOR_PURPLE="\033[1;35m"
COLOR_YELLOW="\033[1;33m"
COLOR_NONE="\033[0m"

# Files to link directly into $HOME (git still reads ~/.gitconfig and the
# core.excludesfile from there). gitmessage.txt is no longer listed: the
# commit template resolves through the ~/.config/git symlink instead.
linkables=(
  "git/.gitconfig"
  "git/.gitignore"
)

# Configuration home
config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"

# config/codex is not a plain whole-directory symlink like the other config/*
# dirs: config.toml mixes portable settings with machine state (trusted
# project list, hook trust hashes, notify path). It gets its own real
# directory at the target with per-entry symlinks, and a generated
# config.toml — see codex_link()/codex_generate_config() below.
codex_source_dir="$DOTFILES/config/codex"
codex_target_dir="$config_home/codex"
codex_generated_header="# Generated by install.sh from config.toml + config.local.toml. Do not edit this file directly on a machine where it is a live symlink target; edit the sources in the dotfiles repo instead."

DRY_RUN=0
NON_INTERACTIVE=0

title() {
  echo -e "\n${COLOR_PURPLE}$1${COLOR_NONE}"
  echo -e "${COLOR_GRAY}==============================${COLOR_NONE}\n"
}

error() {
  echo -e "${COLOR_RED}Error: ${COLOR_NONE}$1"
  exit 1
}

warning() {
  echo -e "${COLOR_YELLOW}Warning: ${COLOR_NONE}$1"
}

info() {
  echo -e "${COLOR_BLUE}Info: ${COLOR_NONE}$1"
}

success() {
  echo -e "${COLOR_GREEN}$1${COLOR_NONE}"
}

# ---------------------------------------------------------------------------
# Dry-run-aware primitives. Every mutating filesystem call in this script
# goes through one of these so `--dry-run` can describe the plan without
# touching anything.
# ---------------------------------------------------------------------------

do_mkdir() {
  if ((DRY_RUN)); then
    info "[dry-run] mkdir -p $1"
  else
    mkdir -p "$1"
  fi
}

do_link() {
  if ((DRY_RUN)); then
    info "[dry-run] ln -s $1 -> $2"
  else
    ln -s "$1" "$2"
  fi
}

do_rm() {
  if ((DRY_RUN)); then
    info "[dry-run] rm $1"
  else
    rm "$1"
  fi
}

do_copy() {
  if ((DRY_RUN)); then
    info "[dry-run] cp -R $1 -> $2"
  else
    cp -R "$1" "$2"
  fi
}

# Only remove a symlink if it still points at the repo path we created it
# with. Protects unrelated symlinks a user may have placed at the same name
# (e.g. a hand-made ~/bin) from being deleted by `clean`.
remove_if_linked_to() {
  local target="$1" expected_source="$2"
  if [ -L "$target" ]; then
    if [ "$(readlink "$target")" = "$expected_source" ]; then
      info "Cleaning up \"$target\""
      do_rm "$target"
    else
      warning "Skipping \"$target\" because it is a symlink to something else"
    fi
  elif [ -e "$target" ]; then
    warning "Skipping \"$target\" because it is not a symlink"
  else
    warning "Skipping \"$target\" because it does not exist"
  fi
}

# ---------------------------------------------------------------------------
# codex: real target directory, per-entry symlinks, generated config.toml
# ---------------------------------------------------------------------------

codex_generate_config() {
  local portable="$codex_source_dir/config.toml"
  local overlay="$codex_source_dir/config.local.toml"
  local out="$codex_target_dir/config.toml"

  if ((DRY_RUN)); then
    if [ -f "$overlay" ]; then
      info "[dry-run] generate $out from config.toml + config.local.toml"
    else
      info "[dry-run] generate $out from config.toml (no local overlay present)"
    fi
    return 0
  fi

  # Naive concatenation would leave config.local.toml's bare top-level keys
  # (e.g. `notify = [...]`) scoped inside whatever `[table]` config.toml last
  # opened, instead of at the document root. Split each file at its first
  # `[table]` header line and interleave: leading bare keys from both files
  # first, then every table section, so `notify` stays a real top-level key.
  {
    echo "$codex_generated_header"
    echo
    awk '/^\[/{exit} {print}' "$portable"
    if [ -f "$overlay" ]; then
      awk '/^\[/{exit} {print}' "$overlay"
    fi
    echo
    awk 'f{print;next} /^\[/{f=1; print}' "$portable"
    if [ -f "$overlay" ]; then
      echo
      echo "# ---- machine-local overlay: config.local.toml ----"
      awk 'f{print} /^\[/{f=1; print}' "$overlay"
    fi
  } >"$out"
}

# Per-entry symlink everything in config/codex except the files the merge
# step owns (config.toml, and the local overlay + its tracked example never
# need to appear at the target at all).
codex_link_entries() {
  do_mkdir "$codex_target_dir"
  while IFS= read -r -d '' entry; do
    name="$(basename "$entry")"
    case "$name" in
    config.toml | config.local.toml | config.local.toml.example) continue ;;
    esac
    target="$codex_target_dir/$name"
    if [ -e "$target" ] || [ -L "$target" ]; then
      info "~${target#"$HOME"} already exists... Skipping."
    else
      do_link "$entry" "$target"
    fi
  done < <(find "$codex_source_dir" -mindepth 1 -maxdepth 1 -print0)
}

# Seeds config.toml the first time only. Re-running `link` must not clobber
# a live config.toml that Codex itself has since written trusted-project or
# hook-trust entries into — use `install.sh codex-sync` to force a refresh.
codex_link() {
  codex_link_entries
  local out="$codex_target_dir/config.toml"
  if [ -e "$out" ] || [ -L "$out" ]; then
    info "~${out#"$HOME"} already exists... Skipping (run 'install.sh codex-sync' to regenerate)."
  else
    codex_generate_config
  fi
}

codex_sync() {
  title "Regenerating Codex config.toml"
  if [ ! -d "$codex_target_dir" ]; then
    error "codex target directory does not exist yet: $codex_target_dir (run 'install.sh link' first)"
  fi
  warning "This overwrites $codex_target_dir/config.toml. Any trusted-project or hook-trust entries Codex has written since the last sync must already be copied into config.local.toml, or they will be lost."
  codex_generate_config
  success "config.toml regenerated."
}

codex_clean() {
  [ -d "$codex_target_dir" ] || return 0
  while IFS= read -r -d '' entry; do
    name="$(basename "$entry")"
    [ "$name" = "config.toml" ] && continue
    target="$codex_source_dir/$name"
    remove_if_linked_to "$entry" "$target"
  done < <(find "$codex_target_dir" -mindepth 1 -maxdepth 1 -print0)

  local generated="$codex_target_dir/config.toml"
  if [ -f "$generated" ] && grep -qF "$codex_generated_header" "$generated" 2>/dev/null; then
    info "Cleaning up \"$generated\""
    if ! ((DRY_RUN)); then rm "$generated"; fi
  elif [ -e "$generated" ]; then
    warning "Skipping \"$generated\" because it was not generated by install.sh (Codex may have rewritten it)"
  fi

  if ((DRY_RUN)); then
    info "[dry-run] rmdir $codex_target_dir (if empty)"
  else
    rmdir "$codex_target_dir" 2>/dev/null || warning "\"$codex_target_dir\" is not empty, leaving it in place"
  fi
}

codex_copy() {
  do_mkdir "$codex_target_dir"
  while IFS= read -r -d '' entry; do
    name="$(basename "$entry")"
    case "$name" in
    config.local.toml | config.local.toml.example) continue ;;
    esac
    do_copy "$entry" "$codex_target_dir/$name"
  done < <(find "$codex_source_dir" -mindepth 1 -maxdepth 1 -print0)
  codex_generate_config
}

# ---------------------------------------------------------------------------
# managed targets: backup, link, clean, and copy all walk the same manifest
# (linkables[] + non-codex config/* dirs + the codex special case + .zshenv +
# ~/bin) instead of each hardcoding its own list.
# ---------------------------------------------------------------------------

# NUL-safe: filenames with spaces or newlines don't break iteration.
non_codex_config_dirs() {
  find "$DOTFILES/config" -mindepth 1 -maxdepth 1 -type d ! -name codex -print0 2>/dev/null
}

backup() {
  title "Backing up existing dotfiles"
  BACKUP_DIR="$HOME/dotfiles-backup"

  echo "Creating backup directory at $BACKUP_DIR"
  do_mkdir "$BACKUP_DIR"

  # ${linkables[@]+...} keeps the expansion safe under `set -u` on bash 3.2
  # (macOS stock bash) when the array is empty.
  for file in ${linkables[@]+"${linkables[@]}"}; do
    filename="$(basename "$file")"
    target="$HOME/$filename"
    if [ -f "$target" ] && [ ! -L "$target" ]; then
      echo "backing up $filename"
      do_copy "$target" "$BACKUP_DIR"
    else
      warning "$filename does not exist at this location or is a symlink"
    fi
  done

  for filename in "$HOME/.config/nvim" "$HOME/.vim" "$HOME/.vimrc" "$HOME/.zshenv"; do
    if [ -e "$filename" ] && [ ! -L "$filename" ]; then
      echo "backing up $filename"
      if ((DRY_RUN)); then
        info "[dry-run] cp -rf $filename -> $BACKUP_DIR"
      else
        cp -rf "$filename" "$BACKUP_DIR"
      fi
    else
      warning "$filename does not exist at this location or is a symlink"
    fi
  done

  while IFS= read -r -d '' config; do
    target="$config_home/$(basename "$config")"
    if [ -e "$target" ] && [ ! -L "$target" ]; then
      echo "backing up $target"
      if ((DRY_RUN)); then
        info "[dry-run] cp -rf $target -> $BACKUP_DIR"
      else
        cp -rf "$target" "$BACKUP_DIR"
      fi
    else
      warning "$target does not exist at this location or is a symlink"
    fi
  done < <(non_codex_config_dirs)

  if [ -e "$codex_target_dir" ] && [ ! -L "$codex_target_dir" ]; then
    echo "backing up $codex_target_dir"
    if ((DRY_RUN)); then
      info "[dry-run] cp -rf $codex_target_dir -> $BACKUP_DIR"
    else
      cp -rf "$codex_target_dir" "$BACKUP_DIR"
    fi
  else
    warning "$codex_target_dir does not exist at this location or is a symlink"
  fi

  if [ -e "$HOME/bin" ] && [ ! -L "$HOME/bin" ]; then
    echo "backing up $HOME/bin"
    if ((DRY_RUN)); then
      info "[dry-run] cp -rf $HOME/bin -> $BACKUP_DIR"
    else
      cp -rf "$HOME/bin" "$BACKUP_DIR"
    fi
  else
    warning "$HOME/bin does not exist at this location or is a symlink"
  fi
}

cleanup_symlinks() {
  title "Cleaning up symlinks"
  for file in ${linkables[@]+"${linkables[@]}"}; do
    target="$HOME/$(basename "$file")"
    remove_if_linked_to "$target" "$DOTFILES/config/$file"
  done

  remove_if_linked_to "$HOME/.zshenv" "$DOTFILES/config/zsh/.zshenv"
  remove_if_linked_to "$HOME/bin" "$DOTFILES/bin"

  echo -e
  info "cleaning up $config_home"

  while IFS= read -r -d '' config; do
    target="$config_home/$(basename "$config")"
    remove_if_linked_to "$target" "$config"
  done < <(non_codex_config_dirs)

  codex_clean
}

setup_symlinks() {
  title "Creating symlinks"

  for file in ${linkables[@]+"${linkables[@]}"}; do
    target="$HOME/$(basename "$file")"
    # `-L` (not just `-e`) so a broken symlink left at $target is treated as
    # "already there" instead of falling through to a failing `ln -s`, which
    # used to be silently swallowed and still report success (audit #1).
    if [ -e "$target" ] || [ -L "$target" ]; then
      info "~${target#"$HOME"} already exists... Skipping."
    else
      info "Creating symlink for $file"
      do_link "$DOTFILES/config/$file" "$target"
    fi
  done

  echo -e
  info "installing to $config_home"
  if [ ! -d "$config_home" ]; then
    info "Creating $config_home"
    do_mkdir "$config_home"
  fi

  if [ ! -d "$data_home" ]; then
    info "Creating $data_home"
    do_mkdir "$data_home"
  fi

  while IFS= read -r -d '' config; do
    target="$config_home/$(basename "$config")"
    if [ -e "$target" ] || [ -L "$target" ]; then
      info "~${target#"$HOME"} already exists... Skipping."
    else
      info "Creating symlink for $config"
      do_link "$config" "$target"
    fi
  done < <(non_codex_config_dirs)

  codex_link

  # symlink .zshenv into home directory to properly setup ZSH
  if [ ! -e "$HOME/.zshenv" ] && [ ! -L "$HOME/.zshenv" ]; then
    info "Creating symlink for .zshenv"
    do_link "$DOTFILES/config/zsh/.zshenv" "$HOME/.zshenv"
  else
    info "$HOME/.zshenv already exists... Skipping."
  fi

  # Define source and target paths
  source_path="$DOTFILES/bin"
  target_path="$HOME/bin"

  # Create symlink for /bin folder
  echo -e
  info "Creating symlink for /bin folder..."
  # Check if source directory exists
  if [ ! -d "$source_path" ]; then
    warning "Source directory does not exist: $source_path"
    return 1
  fi

  # Check if target already exists.
  # NOTE: these must be `return`, not `exit` — an `exit` here aborts the whole
  # script, which silently skipped homebrew/shell/git/macos in `./install.sh all`.
  # Under `set -e` a non-zero `return` from this function now aborts the
  # script with a non-zero exit instead of falling through to "Done." (#1).
  if [ -L "$target_path" ]; then
    info "Symlink already exists at $target_path - Skipping."
    return 0
  elif [ -e "$target_path" ]; then
    # If target exists but is not a symlink
    warning "Target path exists but is not a symlink: $target_path"
    return 1
  fi

  # Create symlink
  if ((DRY_RUN)); then
    info "[dry-run] ln -s $source_path -> $target_path"
  elif ln -s "$source_path" "$target_path"; then
    echo "Successfully created symlink: $target_path -> $source_path"
  else
    echo "Failed to create symlink: $target_path -> $source_path"
    return 1
  fi
}

copy() {
  title "Copying configs"
  if [ ! -d "$config_home" ]; then
    info "Creating $config_home"
    do_mkdir "$config_home"
  fi

  if [ ! -d "$data_home" ]; then
    info "Creating $data_home"
    do_mkdir "$data_home"
  fi

  for file in ${linkables[@]+"${linkables[@]}"}; do
    target="$HOME/$(basename "$file")"
    info "copying $file to $target"
    do_copy "$DOTFILES/config/$file" "$target"
  done

  while IFS= read -r -d '' config; do
    target="$config_home/$(basename "$config")"
    info "copying $config to $target"
    do_copy "$config" "$target"
  done < <(non_codex_config_dirs)

  codex_copy

  info "copying .zshenv to $HOME/.zshenv"
  do_copy "$DOTFILES/config/zsh/.zshenv" "$HOME/.zshenv"

  info "copying bin to $HOME/bin"
  do_copy "$DOTFILES/bin" "$HOME/bin"
}

setup_git() {
  title "Setting up Git"

  if ((NON_INTERACTIVE)) || [[ ! -t 0 ]]; then
    warning "Skipping interactive git setup (non-interactive or no TTY). Set git config manually or re-run './install.sh git' from a terminal."
    return 0
  fi

  # `git config` exits non-zero when the key is unset — expected, not a
  # failure, so it must not trip `set -e`.
  defaultName=$(git config user.name || true)
  defaultEmail=$(git config user.email || true)
  defaultGithub=$(git config github.user || true)

  read -rp "Name [$defaultName] " name
  read -rp "Email [$defaultEmail] " email
  read -rp "Github username [$defaultGithub] " github

  git config -f ~/.gitconfig-local user.name "${name:-$defaultName}"
  git config -f ~/.gitconfig-local user.email "${email:-$defaultEmail}"
  git config -f ~/.gitconfig-local github.user "${github:-$defaultGithub}"

  if [[ "$(uname)" == "Darwin" ]]; then
    git config --global credential.helper "osxkeychain"
  else
    read -rn 1 -p "Save user and password to an unencrypted file to avoid writing? [y/N] " save
    if [[ $save =~ ^([Yy])$ ]]; then
      git config --global credential.helper "store"
    else
      git config --global credential.helper "cache --timeout 3600"
    fi
  fi
}

setup_homebrew() {
  title "Setting up Homebrew"

  if test ! "$(command -v brew)"; then
    info "Homebrew not installed. Installing."
    # Run as a login shell (non-interactive) so that the script doesn't pause for user input
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash --login
  fi

  if [ "$(uname)" == "Linux" ]; then
    test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
    test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
  fi

  # install brew dependencies from Brewfile
  brew bundle --file="$DOTFILES/Brewfile"

  # install fzf
  echo -e
  info "Installing fzf"
  "$(brew --prefix)"/opt/fzf/install --key-bindings --completion --no-update-rc --no-bash --no-fish
}

setup_shell() {
  title "Configuring shell"

  [[ -n "$(command -v brew)" ]] && zsh_path="$(brew --prefix)/bin/zsh" || zsh_path="$(command -v zsh)"
  if ! grep -qx "$zsh_path" /etc/shells; then
    info "adding $zsh_path to /etc/shells"
    echo "$zsh_path" | sudo tee -a /etc/shells
  fi

  if [[ "$SHELL" != "$zsh_path" ]]; then
    sudo chsh -s "$zsh_path" "$(whoami)"
    info "default shell changed to $zsh_path"
  fi

  local zinit_home="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"
  if [ ! -d "$zinit_home" ]; then
    info "Installing Zinit (first interactive shell start no longer has to do this over the network)"
    if ((DRY_RUN)); then
      info "[dry-run] git clone https://github.com/zdharma-continuum/zinit.git $zinit_home"
    else
      do_mkdir "$(dirname "$zinit_home")"
      git clone https://github.com/zdharma-continuum/zinit.git "$zinit_home"
    fi
  else
    info "Zinit already installed at $zinit_home... Skipping."
  fi
}

setup_macos() {
  title "Configuring macOS"
  if [[ "$(uname)" == "Darwin" ]]; then

    echo "Finder: show all filename extensions"
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true

    echo "show hidden files by default"
    defaults write com.apple.Finder AppleShowAllFiles -bool true

    echo "only use UTF-8 in Terminal.app"
    defaults write com.apple.terminal StringEncodings -array 4

    echo "expand save dialog by default"
    defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

    echo "show the ~/Library folder in Finder"
    chflags nohidden ~/Library

    echo "Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)"
    defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

    echo "Enable subpixel font rendering on non-Apple LCDs"
    defaults write NSGlobalDomain AppleFontSmoothing -int 2

    echo "Show Path bar in Finder"
    defaults write com.apple.finder ShowPathbar -bool true

    echo "Show Status bar in Finder"
    defaults write com.apple.finder ShowStatusBar -bool true

    echo "the default Finder view to list view"
    defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

    echo "default list view settings for new folders"
    defaults write com.apple.finder FK_StandardViewSettings -dict-add ListViewSettings '{ "columns" = ( { "ascending" = 1; "identifier" = "name"; "visible" = 1; "width" = 300; }, { "ascending" = 0; "identifier" = "dateModified"; "visible" = 1; "width" = 181; }, { "ascending" = 0; "identifier" = "size"; "visible" = 1; "width" = 97; } ); "iconSize" = 16; "showIconPreview" = 0; "sortColumn" = "name"; "textSize" = 12; "useRelativeDates" = 1; }'

    echo "existing folder view settings to force use of default settings"
    defaults delete com.apple.finder FXInfoPanesExpanded 2>/dev/null || true
    defaults delete com.apple.finder FXDesktopVolumePositions 2>/dev/null || true

    echo "Set list view for all view types"
    defaults write com.apple.finder FK_StandardViewSettings -dict-add ExtendedListViewSettings '{ "columns" = ( { "ascending" = 1; "identifier" = "name"; "visible" = 1; "width" = 300; }, { "ascending" = 0; "identifier" = "dateModified"; "visible" = 1; "width" = 181; }, { "ascending" = 0; "identifier" = "size"; "visible" = 1; "width" = 97; } ); "iconSize" = 16; "showIconPreview" = 0; "sortColumn" = "name"; "textSize" = 12; "useRelativeDates" = 1; }'

    echo "default search scope to the current folder"
    defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

    echo "trash items older than 30 days"
    defaults write com.apple.finder "FXRemoveOldTrashItems" -bool "true"

    echo "Remove .DS_Store files to reset folder view settings"
    find ~ -name ".DS_Store" -type f -delete 2>/dev/null || true

    echo "Show all filename extensions"
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true

    echo "Enable Safari’s debug menu"
    defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

    echo "Kill affected applications"

    # `|| true`: it's normal for some of these apps not to be running.
    for app in Safari Finder Dock Mail SystemUIServer; do killall "$app" >/dev/null 2>&1 || true; done
  else
    warning "macOS not detected. Skipping."
  fi
}

setup_hooks() {
  title "Installing git hooks"
  # core.hooksPath over symlinking into .git/hooks: one idempotent git-config
  # call, no per-hook symlink/chmod bookkeeping, and it keeps working from any
  # worktree of this repo (a worktree's .git is a file, not the hooks dir).
  if ((DRY_RUN)); then
    info "[dry-run] git -C \"$DOTFILES\" config core.hooksPath githooks"
  else
    git -C "$DOTFILES" config core.hooksPath githooks
  fi
  success "core.hooksPath set to githooks/ — githooks/pre-commit now runs on commit."
}

usage() {
  cat <<EOF

Usage: $(basename "$0") [--dry-run] [--non-interactive] <command>

Commands:
  backup           Back up existing dotfiles to ~/dotfiles-backup/
  clean            Remove symlinks created by link
  link             Create symlinks from config/ -> \$XDG_CONFIG_HOME and bin/ -> ~/bin
  copy             Copy configs instead of symlinking (useful for containers)
  codex-sync       Regenerate \$XDG_CONFIG_HOME/codex/config.toml from config.toml + config.local.toml
  hooks            Install githooks/pre-commit via 'git config core.hooksPath'
  git              Set up Git identity and credential helper
  homebrew         Install Homebrew and run 'brew bundle' from the Brewfile
  shell            Set Zsh as the default shell and pre-install Zinit
  macos            Apply macOS system preferences
  all              Run link -> homebrew -> shell -> git -> macos
  help             Show this message

Flags:
  --dry-run         Print what would change without touching the filesystem
  --non-interactive Skip prompts (currently: the git identity prompts)

EOF
}

# ---------------------------------------------------------------------------
# Argument parsing: pull flags out of argv wherever they appear, leaving the
# first remaining word as the subcommand.
# ---------------------------------------------------------------------------
args=()
for arg in "$@"; do
  case "$arg" in
  --dry-run) DRY_RUN=1 ;;
  --non-interactive) NON_INTERACTIVE=1 ;;
  *) args+=("$arg") ;;
  esac
done

if ((DRY_RUN)); then
  info "--dry-run: no filesystem changes will be made"
fi

case "${args[0]:-}" in
backup)
  backup
  ;;
clean)
  cleanup_symlinks
  ;;
link)
  setup_symlinks
  ;;
copy)
  copy
  ;;
codex-sync)
  codex_sync
  ;;
hooks)
  setup_hooks
  ;;
git)
  setup_git
  ;;
homebrew)
  setup_homebrew
  ;;
shell)
  setup_shell
  ;;
macos)
  setup_macos
  ;;
all)
  setup_symlinks
  setup_homebrew
  setup_shell
  setup_git
  setup_macos
  ;;
help | -h | --help)
  usage
  exit 0
  ;;
*)
  usage
  exit 1
  ;;
esac

echo -e
success "Done."
