#!/usr/bin/env bash

# `-e` (errexit): a real failure (broken symlink collision, a missing source
# dir, a bad copy) now aborts with a non-zero exit instead of printing
# "Done." anyway. Every place a non-zero exit is *expected* (existence
# probes, optional cleanups, `git config` on an unset key) is localized with
# `|| true`, an `if`, or a `&&`/`||` list — see the comments below.
set -Eeuo pipefail

# Resolve the repo root from the script's own location so the installer works
# no matter which directory it is invoked from.
DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COLOR_GRAY="\033[1;38;5;243m"
COLOR_BLUE="\033[1;34m"
COLOR_GREEN="\033[1;32m"
COLOR_RED="\033[1;31m"
COLOR_PURPLE="\033[1;35m"
COLOR_YELLOW="\033[1;33m"
COLOR_NONE="\033[0m"

# Files to link directly into $HOME (git still reads ~/.gitconfig and the
# core.excludesfile from there). gitmessage.txt is no longer listed: the
# commit template resolves through the ~/.config/git symlink instead.
linkables=(
  "git/.gitconfig"
  "git/.gitignore"
  "AGENTS.md"
)

# Configuration home
config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"

# ---------------------------------------------------------------------------
# Agent tool homes. Every agent tool keeps its own native default directory
# as the real directory - Claude Code ~/.claude, Codex ~/.codex, Copilot CLI
# ~/.copilot - and the repo only links its tracked content into that
# directory entry by entry. No environment variable relocates a tool's home:
# Claude Code honours CLAUDE_CONFIG_DIR, but third-party tools (quota-axi,
# GUI launchers that never source the shell) re-derive keychain names and
# paths from the defaults, so a relocated home broke them. OpenCode's native
# home is already $XDG_CONFIG_HOME/opencode, so config/opencode stays a plain
# whole-directory symlink like the other config/* dirs.
#
# Machine state (settings, auth, sessions, history, sqlite, plugin caches)
# lives next to the links inside each home and never inside the repo.
# ---------------------------------------------------------------------------
claude_source_dir="$DOTFILES/config/claude"
claude_home="$HOME/.claude"
codex_source_dir="$DOTFILES/config/codex"
codex_home="$HOME/.codex"
copilot_source_dir="$DOTFILES/config/copilot"
copilot_home="$HOME/.copilot"
codex_generated_header="# Generated by install.sh from config.toml + config.local.toml. Do not edit this file directly; edit the sources in the dotfiles repo and run 'install.sh codex-sync'."

DRY_RUN=0
NON_INTERACTIVE=0

title() {
  echo -e "\n${COLOR_PURPLE}$1${COLOR_NONE}"
  echo -e "${COLOR_GRAY}==============================${COLOR_NONE}\n"
}

error() {
  echo -e "${COLOR_RED}Error: ${COLOR_NONE}$1"
  exit 1
}

warning() {
  echo -e "${COLOR_YELLOW}Warning: ${COLOR_NONE}$1"
}

info() {
  echo -e "${COLOR_BLUE}Info: ${COLOR_NONE}$1"
}

success() {
  echo -e "${COLOR_GREEN}$1${COLOR_NONE}"
}

# ---------------------------------------------------------------------------
# Dry-run-aware primitives. Every mutating filesystem call in this script
# goes through one of these so `--dry-run` can describe the plan without
# touching anything.
# ---------------------------------------------------------------------------

do_mkdir() {
  if ((DRY_RUN)); then
    info "[dry-run] mkdir -p $1"
  else
    mkdir -p "$1"
  fi
}

do_link() {
  if ((DRY_RUN)); then
    info "[dry-run] ln -s $1 -> $2"
  else
    ln -s "$1" "$2"
  fi
}

do_rm() {
  if ((DRY_RUN)); then
    info "[dry-run] rm $1"
  else
    rm "$1"
  fi
}

do_copy() {
  if ((DRY_RUN)); then
    info "[dry-run] cp -R $1 -> $2"
  else
    cp -R "$1" "$2"
  fi
}

# Only remove a symlink if it still points at the repo path we created it
# with. Protects unrelated symlinks a user may have placed at the same name
# (e.g. a hand-made ~/bin) from being deleted by `clean`.
remove_if_linked_to() {
  local target="$1" expected_source="$2"
  if [ -L "$target" ]; then
    if [ "$(readlink "$target")" = "$expected_source" ]; then
      info "Cleaning up \"$target\""
      do_rm "$target"
    else
      warning "Skipping \"$target\" because it is a symlink to something else"
    fi
  elif [ -e "$target" ]; then
    warning "Skipping \"$target\" because it is not a symlink"
  else
    warning "Skipping \"$target\" because it does not exist"
  fi
}

# ---------------------------------------------------------------------------
# Agent home primitives shared by claude/codex/copilot.
# ---------------------------------------------------------------------------

# link/skills never delete or overwrite anything inside an agent home. When a
# target that should become a real directory is a symlink (an old
# ~/.claude -> ~/.config/claude layout), or a real file/dir or a foreign
# symlink sits where a repo link belongs, the entry is reported and skipped;
# the run then fails at the end so the conflicts cannot go unnoticed.
LINK_CONFLICTS=0

conflict() {
  LINK_CONFLICTS=$((LINK_CONFLICTS + 1))
  warning "$1"
}

fail_on_conflicts() {
  ((LINK_CONFLICTS)) || return 0
  error "$LINK_CONFLICTS conflict(s) were left untouched (nothing was deleted or overwritten). Move each conflicting path listed above out of the way (an old ~/.config/{claude,codex,copilot} directory, or a real file/directory sitting where a link belongs), then re-run 'install.sh link'."
}

# Warn when the current shell still carries the variables the old layout
# relied on; a new shell after pulling the dotfiles no longer exports them.
warn_stale_env() {
  local var
  for var in CLAUDE_CONFIG_DIR CLAUDE_SECURESTORAGE_CONFIG_DIR CODEX_HOME COPILOT_HOME; do
    if [ -n "${!var+x}" ]; then
      warning "$var is still set in this shell (${!var}). It no longer comes from config/zsh/.zshenv; open a new shell (or 'unset $var') so the tool uses its native home."
    fi
  done
}

# NUL-separated top-level entries of config/<tool> that git tracks. Under the
# old layout Codex wrote sessions, auth.json and sqlite files straight into
# the repo dir (they are gitignored), and those must never be linked into a
# home. Falls back to a plain listing when the tree carries no git metadata
# (the Docker image copies the repo without .git).
tracked_entries() {
  local tool="$1" path
  local dir="$DOTFILES/config/$tool"
  if [ -n "$(git -C "$DOTFILES" ls-files -- "config/$tool" 2>/dev/null | head -n 1)" ]; then
    git -C "$DOTFILES" ls-files -z --full-name -- "config/$tool" |
      while IFS= read -r -d '' path; do
        path="${path#config/"$tool"/}"
        printf '%s\0' "$dir/${path%%/*}"
      done | sort -zu
  else
    find "$dir" -mindepth 1 -maxdepth 1 ! -name .DS_Store -print0 2>/dev/null
  fi
}

# The home must be a real directory. A symlink there is the old compatibility
# layout and is reported instead of being replaced.
check_agent_home() {
  local home="$1"
  if [ -L "$home" ]; then
    conflict "~${home#"$HOME"} is a symlink to $(readlink "$home"); it must be a real directory (old layout)."
    return 1
  elif [ -e "$home" ] && [ ! -d "$home" ]; then
    conflict "~${home#"$HOME"} exists but is not a directory."
    return 1
  fi
  return 0
}

# Both checks run so one pass reports every problem; the tool is skipped
# entirely (no mkdir, no links) if either fails.
ensure_agent_home() {
  local home="$1" old="$2" tool="$3" ok=1
  refuse_old_layout_dir "$old" "$tool" || ok=0
  check_agent_home "$home" || ok=0
  ((ok)) || return 1
  do_mkdir "$home"
}

# Leftovers of the old layout: state or links under $XDG_CONFIG_HOME that a
# shell still exporting the old variables would keep writing to. Reported, and
# the whole tool is skipped, so the migration is done deliberately instead of
# leaving two half-used homes.
refuse_old_layout_dir() {
  local old="$1" tool="$2"
  if [ -L "$old" ] || [ -e "$old" ]; then
    conflict "~${old#"$HOME"} exists; move it aside (or remove it if it is only the old compatibility symlink) before re-running 'install.sh link'."
    return 1
  fi
  return 0
}

# Idempotent: a link that already resolves to the repo entry is left alone.
link_agent_entry() {
  local source="$1" target="$2"
  if [ -L "$target" ]; then
    if [ "$target" -ef "$source" ]; then
      return 0
    fi
    conflict "~${target#"$HOME"} is a symlink to $(readlink "$target"); expected $source."
  elif [ -d "$target" ]; then
    conflict "~${target#"$HOME"} is a real directory; expected a symlink to $source."
  elif [ -e "$target" ]; then
    conflict "~${target#"$HOME"} is a real file; expected a symlink to $source."
  else
    info "Linking ~${target#"$HOME"} -> ${source#"$DOTFILES"/}"
    do_link "$source" "$target"
  fi
}

# Remove symlinks in $dir that point into $source_dir but no longer resolve
# (an entry that was deleted from the repo). Only our own dangling links.
prune_dangling_links() {
  local dir="$1" source_dir="$2" link dest
  [ -d "$dir" ] || return 0
  while IFS= read -r -d '' link; do
    dest="$(readlink "$link")"
    case "$dest" in
    "$source_dir"/*) ;;
    *) continue ;;
    esac
    if [ ! -e "$link" ]; then
      info "Pruning dangling link ~${link#"$HOME"} -> $dest"
      do_rm "$link"
    fi
  done < <(find "$dir" -mindepth 1 -maxdepth 1 -type l -print0 2>/dev/null)
}

# clean: remove only the links we created; machine state stays. The home
# itself is left in place (it is the tool's own directory, not ours).
clean_agent_entries() {
  local home="$1" source_dir="$2" entry
  [ -d "$home" ] || return 0
  while IFS= read -r -d '' entry; do
    dest="$(readlink "$entry")"
    case "$dest" in
    "$source_dir"/*) remove_if_linked_to "$entry" "$dest" ;;
    esac
  done < <(find "$home" -mindepth 1 -maxdepth 1 -type l -print0 2>/dev/null)
}

# ---------------------------------------------------------------------------
# codex: real ~/.codex, per-entry links of the tracked config/codex entries,
# generated config.toml
# ---------------------------------------------------------------------------

codex_generate_config() {
  local portable="$codex_source_dir/config.toml"
  local overlay="$codex_source_dir/config.local.toml"
  local out="$codex_home/config.toml"

  if ((DRY_RUN)); then
    if [ -f "$overlay" ]; then
      info "[dry-run] generate $out from config.toml + config.local.toml"
    else
      info "[dry-run] generate $out from config.toml (no local overlay present)"
    fi
    return 0
  fi

  # Naive concatenation would leave config.local.toml's bare top-level keys
  # (e.g. `notify = [...]`) scoped inside whatever `[table]` config.toml last
  # opened, instead of at the document root. Split each file at its first
  # `[table]` header line and interleave: leading bare keys from both files
  # first, then every table section, so `notify` stays a real top-level key.
  {
    echo "$codex_generated_header"
    echo
    awk '/^\[/{exit} {print}' "$portable"
    if [ -f "$overlay" ]; then
      awk '/^\[/{exit} {print}' "$overlay"
    fi
    echo
    awk 'f{print;next} /^\[/{f=1; print}' "$portable"
    if [ -f "$overlay" ]; then
      echo
      echo "# ---- machine-local overlay: config.local.toml ----"
      awk 'f{print;next} /^\[/{f=1; print}' "$overlay"
    fi
  } >"$out"
}

# Everything tracked in config/codex except the files the merge step owns
# (config.toml; the local overlay and its example never appear at the target).
codex_entries() {
  local entry name
  while IFS= read -r -d '' entry; do
    name="$(basename "$entry")"
    case "$name" in
    config.toml | config.local.toml | config.local.toml.example) continue ;;
    esac
    printf '%s\0' "$entry"
  done < <(tracked_entries codex)
}

# Seeds config.toml the first time only. Re-running `link` must not clobber
# a live config.toml that Codex itself has since written trusted-project or
# hook-trust entries into - use `install.sh codex-sync` to force a refresh.
codex_link() {
  ensure_agent_home "$codex_home" "$config_home/codex" codex || return 0
  local entry
  while IFS= read -r -d '' entry; do
    link_agent_entry "$entry" "$codex_home/$(basename "$entry")"
  done < <(codex_entries)
  prune_dangling_links "$codex_home" "$codex_source_dir"

  local out="$codex_home/config.toml"
  if [ -e "$out" ] || [ -L "$out" ]; then
    info "~${out#"$HOME"} already exists... Skipping (run 'install.sh codex-sync' to regenerate)."
  else
    codex_generate_config
  fi
}

codex_sync() {
  title "Regenerating Codex config.toml"
  if [ ! -d "$codex_home" ] || [ -L "$codex_home" ]; then
    error "$codex_home is not a real directory yet (run 'install.sh link' first; if it's a symlink to an old ~/.config/codex layout, move that aside first)"
  fi
  warning "This overwrites $codex_home/config.toml. Any trusted-project or hook-trust entries Codex has written since the last sync must already be copied into config.local.toml, or they will be lost."
  codex_generate_config
  success "config.toml regenerated."
}

codex_clean() {
  clean_agent_entries "$codex_home" "$codex_source_dir"
  local generated="$codex_home/config.toml"
  if [ -f "$generated" ] && grep -qF "$codex_generated_header" "$generated" 2>/dev/null; then
    info "Cleaning up \"$generated\""
    do_rm "$generated"
  elif [ -e "$generated" ]; then
    warning "Skipping \"$generated\" because it was not generated by install.sh (Codex may have rewritten it)"
  fi
}

codex_copy() {
  do_mkdir "$codex_home"
  local entry
  while IFS= read -r -d '' entry; do
    do_copy "$entry" "$codex_home/$(basename "$entry")"
  done < <(codex_entries)
  codex_generate_config
}

# ---------------------------------------------------------------------------
# claude: real ~/.claude, per-entry links of the tracked config/claude
# entries; skills are linked per skill by setup_skills. ~/.claude.json stays
# at its default location, untouched.
# ---------------------------------------------------------------------------

claude_entries() {
  local entry
  while IFS= read -r -d '' entry; do
    # skills are linked per skill so skills installed outside this repo can
    # live next to them
    [ "$(basename "$entry")" = skills ] && continue
    printf '%s\0' "$entry"
  done < <(tracked_entries claude)
}

# claude_link and claude_skills_link both need a usable ~/.claude. The gate
# runs once per invocation so `link` reports each conflict a single time,
# while a standalone `skills` run still evaluates (and records) it.
CLAUDE_HOME_GATE=""

claude_home_ready() {
  if [ -z "$CLAUDE_HOME_GATE" ]; then
    if ensure_agent_home "$claude_home" "$config_home/claude" claude; then
      CLAUDE_HOME_GATE=ok
    else
      CLAUDE_HOME_GATE=refused
    fi
  fi
  [ "$CLAUDE_HOME_GATE" = ok ]
}

claude_link() {
  claude_home_ready || return 0
  local entry
  while IFS= read -r -d '' entry; do
    link_agent_entry "$entry" "$claude_home/$(basename "$entry")"
  done < <(claude_entries)
  prune_dangling_links "$claude_home" "$claude_source_dir"
}

claude_clean() {
  clean_agent_entries "$claude_home" "$claude_source_dir"
  claude_skills_clean
}

claude_copy() {
  do_mkdir "$claude_home"
  local entry
  while IFS= read -r -d '' entry; do
    do_copy "$entry" "$claude_home/$(basename "$entry")"
  done < <(claude_entries)
  claude_skills_copy
}

# ---------------------------------------------------------------------------
# copilot: real ~/.copilot (Copilot CLI's own directory), per-entry links of
# the tracked config/copilot entries (agents, skills).
# ---------------------------------------------------------------------------

copilot_link() {
  ensure_agent_home "$copilot_home" "$config_home/copilot" copilot || return 0
  local entry
  while IFS= read -r -d '' entry; do
    link_agent_entry "$entry" "$copilot_home/$(basename "$entry")"
  done < <(tracked_entries copilot)
  prune_dangling_links "$copilot_home" "$copilot_source_dir"
}

copilot_clean() {
  clean_agent_entries "$copilot_home" "$copilot_source_dir"
}

copilot_copy() {
  do_mkdir "$copilot_home"
  local entry
  while IFS= read -r -d '' entry; do
    do_copy "$entry" "$copilot_home/$(basename "$entry")"
  done < <(tracked_entries copilot)
}

# ---------------------------------------------------------------------------
# skills: config/skills is the single source. Every harness reads a per-skill
# symlink: the repo-side config/<harness>/skills/<name> -> ../../skills/<name>
# (committed, checked by githooks/skills-lint.py) and, for Claude Code, a
# per-skill link in ~/.claude/skills, which stays a real directory so skills
# installed outside this repo can live next to them. `install.sh skills`
# (also run by `link`) creates any missing links and prunes ones whose shared
# skill was removed.
# ---------------------------------------------------------------------------

skills_source_dir="$DOTFILES/config/skills"
skill_harnesses=(claude codex copilot opencode)
claude_skills_dir="$claude_home/skills"

# NUL-safe list of shared skill directories.
shared_skills() {
  find "$skills_source_dir" -mindepth 1 -maxdepth 1 -type d -print0 2>/dev/null
}

# Ensure config/<harness>/skills/<name> -> ../../skills/<name> for every shared
# skill. Idempotent: existing entries (links or real dirs) are left alone.
harness_skills_link() {
  local harness dir name target
  for harness in "${skill_harnesses[@]}"; do
    dir="$DOTFILES/config/$harness/skills"
    do_mkdir "$dir"
    while IFS= read -r -d '' skill; do
      name="$(basename "$skill")"
      target="$dir/$name"
      if [ -e "$target" ] || [ -L "$target" ]; then
        continue
      fi
      info "Linking skill $name into config/$harness/skills"
      do_link "../../skills/$name" "$target"
    done < <(shared_skills)
  done
}

# Per-skill absolute links into ~/.claude/skills, plus pruning of links that
# point into config/skills but whose skill no longer exists there.
claude_skills_link() {
  claude_home_ready || return 0
  if [ -L "$claude_skills_dir" ]; then
    conflict "~${claude_skills_dir#"$HOME"} must be a real directory inside a real ~${claude_home#"$HOME"} (old layout)."
    return 0
  fi
  do_mkdir "$claude_skills_dir"
  local skill
  while IFS= read -r -d '' skill; do
    link_agent_entry "$skill" "$claude_skills_dir/$(basename "$skill")"
  done < <(shared_skills)
  prune_dangling_links "$claude_skills_dir" "$skills_source_dir"
}

claude_skills_clean() {
  [ -d "$claude_skills_dir" ] || return 0
  while IFS= read -r -d '' skill; do
    name="$(basename "$skill")"
    remove_if_linked_to "$claude_skills_dir/$name" "$skill"
  done < <(shared_skills)
}

claude_skills_copy() {
  do_mkdir "$claude_skills_dir"
  while IFS= read -r -d '' skill; do
    do_copy "$skill" "$claude_skills_dir/$(basename "$skill")"
  done < <(shared_skills)
}

setup_skills() {
  title "Linking skills"
  harness_skills_link
  claude_skills_link
}

# ---------------------------------------------------------------------------
# managed targets: backup, link, clean, and copy all walk the same manifest
# (linkables[] + the whole-directory config/* dirs + the agent homes + .zshenv
# + ~/bin) instead of each hardcoding its own list.
# ---------------------------------------------------------------------------

# NUL-safe: filenames with spaces or newlines don't break iteration.
# claude, codex and copilot are handled by their own functions (real native
# home, per-entry links) and are excluded here.
xdg_config_dirs() {
  find "$DOTFILES/config" -mindepth 1 -maxdepth 1 -type d ! -name codex ! -name claude ! -name copilot -print0 2>/dev/null
}

agent_homes() {
  printf '%s\0' "$claude_home" "$codex_home" "$copilot_home"
}

backup() {
  title "Backing up existing dotfiles"
  BACKUP_DIR="$HOME/dotfiles-backup"

  echo "Creating backup directory at $BACKUP_DIR"
  do_mkdir "$BACKUP_DIR"

  # ${linkables[@]+...} keeps the expansion safe under `set -u` on bash 3.2
  # (macOS stock bash) when the array is empty.
  for file in ${linkables[@]+"${linkables[@]}"}; do
    filename="$(basename "$file")"
    target="$HOME/$filename"
    if [ -f "$target" ] && [ ! -L "$target" ]; then
      echo "backing up $filename"
      do_copy "$target" "$BACKUP_DIR"
    else
      warning "$filename does not exist at this location or is a symlink"
    fi
  done

  for filename in "$HOME/.config/nvim" "$HOME/.vim" "$HOME/.vimrc" "$HOME/.zshenv"; do
    if [ -e "$filename" ] && [ ! -L "$filename" ]; then
      echo "backing up $filename"
      if ((DRY_RUN)); then
        info "[dry-run] cp -rf $filename -> $BACKUP_DIR"
      else
        cp -rf "$filename" "$BACKUP_DIR"
      fi
    else
      warning "$filename does not exist at this location or is a symlink"
    fi
  done

  while IFS= read -r -d '' config; do
    target="$config_home/$(basename "$config")"
    if [ -e "$target" ] && [ ! -L "$target" ]; then
      echo "backing up $target"
      if ((DRY_RUN)); then
        info "[dry-run] cp -rf $target -> $BACKUP_DIR"
      else
        cp -rf "$target" "$BACKUP_DIR"
      fi
    else
      warning "$target does not exist at this location or is a symlink"
    fi
  done < <(xdg_config_dirs)

  while IFS= read -r -d '' home; do
    if [ -e "$home" ] && [ ! -L "$home" ]; then
      echo "backing up $home"
      if ((DRY_RUN)); then
        info "[dry-run] cp -rf $home -> $BACKUP_DIR"
      else
        cp -rf "$home" "$BACKUP_DIR"
      fi
    else
      warning "$home does not exist at this location or is a symlink"
    fi
  done < <(agent_homes)

  if [ -e "$HOME/bin" ] && [ ! -L "$HOME/bin" ]; then
    echo "backing up $HOME/bin"
    if ((DRY_RUN)); then
      info "[dry-run] cp -rf $HOME/bin -> $BACKUP_DIR"
    else
      cp -rf "$HOME/bin" "$BACKUP_DIR"
    fi
  else
    warning "$HOME/bin does not exist at this location or is a symlink"
  fi
}

cleanup_symlinks() {
  title "Cleaning up symlinks"
  for file in ${linkables[@]+"${linkables[@]}"}; do
    target="$HOME/$(basename "$file")"
    remove_if_linked_to "$target" "$DOTFILES/config/$file"
  done

  remove_if_linked_to "$HOME/.zshenv" "$DOTFILES/config/zsh/.zshenv"
  remove_if_linked_to "$HOME/bin" "$DOTFILES/bin"

  echo -e
  info "cleaning up $config_home"

  while IFS= read -r -d '' config; do
    target="$config_home/$(basename "$config")"
    remove_if_linked_to "$target" "$config"
  done < <(xdg_config_dirs)

  codex_clean
  claude_clean
  copilot_clean
}

setup_symlinks() {
  title "Creating symlinks"

  for file in ${linkables[@]+"${linkables[@]}"}; do
    target="$HOME/$(basename "$file")"
    # `-L` (not just `-e`) so a broken symlink left at $target is treated as
    # "already there" instead of falling through to a failing `ln -s`, which
    # used to be silently swallowed and still report success (audit #1).
    if [ -e "$target" ] || [ -L "$target" ]; then
      info "~${target#"$HOME"} already exists... Skipping."
    else
      info "Creating symlink for $file"
      do_link "$DOTFILES/config/$file" "$target"
    fi
  done

  echo -e
  info "installing to $config_home"
  if [ ! -d "$config_home" ]; then
    info "Creating $config_home"
    do_mkdir "$config_home"
  fi

  if [ ! -d "$data_home" ]; then
    info "Creating $data_home"
    do_mkdir "$data_home"
  fi

  while IFS= read -r -d '' config; do
    target="$config_home/$(basename "$config")"
    if [ -e "$target" ] || [ -L "$target" ]; then
      info "~${target#"$HOME"} already exists... Skipping."
    else
      info "Creating symlink for $config"
      do_link "$config" "$target"
    fi
  done < <(xdg_config_dirs)

  echo -e
  info "installing agent tool homes (~/.claude, ~/.codex, ~/.copilot)"
  warn_stale_env
  codex_link
  claude_link
  copilot_link
  setup_skills

  # symlink .zshenv into home directory to properly setup ZSH
  if [ ! -e "$HOME/.zshenv" ] && [ ! -L "$HOME/.zshenv" ]; then
    info "Creating symlink for .zshenv"
    do_link "$DOTFILES/config/zsh/.zshenv" "$HOME/.zshenv"
  else
    info "$HOME/.zshenv already exists... Skipping."
  fi

  # Define source and target paths
  source_path="$DOTFILES/bin"
  target_path="$HOME/bin"

  # Create symlink for /bin folder
  echo -e
  info "Creating symlink for /bin folder..."
  # Check if source directory exists
  if [ ! -d "$source_path" ]; then
    warning "Source directory does not exist: $source_path"
    return 1
  fi

  # Check if target already exists.
  # NOTE: these must be `return`, not `exit` - an `exit` here aborts the whole
  # script, which silently skipped homebrew/shell/git/macos in `./install.sh all`.
  # Under `set -e` a non-zero `return` from this function now aborts the
  # script with a non-zero exit instead of falling through to "Done." (#1).
  if [ -L "$target_path" ]; then
    info "Symlink already exists at $target_path - Skipping."
    return 0
  elif [ -e "$target_path" ]; then
    # Like existing config targets, a copied or user-owned bin is not an error.
    warning "Target path exists but is not a symlink: $target_path - Skipping."
    return 0
  fi

  # Create symlink
  if ((DRY_RUN)); then
    info "[dry-run] ln -s $source_path -> $target_path"
  elif ln -s "$source_path" "$target_path"; then
    echo "Successfully created symlink: $target_path -> $source_path"
  else
    echo "Failed to create symlink: $target_path -> $source_path"
    return 1
  fi
}

copy() {
  title "Copying configs"
  if [ ! -d "$config_home" ]; then
    info "Creating $config_home"
    do_mkdir "$config_home"
  fi

  if [ ! -d "$data_home" ]; then
    info "Creating $data_home"
    do_mkdir "$data_home"
  fi

  for file in ${linkables[@]+"${linkables[@]}"}; do
    target="$HOME/$(basename "$file")"
    info "copying $file to $target"
    do_copy "$DOTFILES/config/$file" "$target"
  done

  while IFS= read -r -d '' config; do
    target="$config_home/$(basename "$config")"
    info "copying $config to $target"
    do_copy "$config" "$target"
  done < <(xdg_config_dirs)

  codex_copy
  claude_copy
  copilot_copy

  info "copying .zshenv to $HOME/.zshenv"
  do_copy "$DOTFILES/config/zsh/.zshenv" "$HOME/.zshenv"

  info "copying bin to $HOME/bin"
  do_copy "$DOTFILES/bin" "$HOME/bin"
}

setup_git() {
  title "Setting up Git"

  if ((NON_INTERACTIVE)) || [[ ! -t 0 ]]; then
    warning "Skipping interactive git setup (non-interactive or no TTY). Set git config manually or re-run './install.sh git' from a terminal."
    return 0
  fi

  # `git config` exits non-zero when the key is unset — expected, not a
  # failure, so it must not trip `set -e`.
  defaultName=$(git config user.name || true)
  defaultEmail=$(git config user.email || true)
  defaultGithub=$(git config github.user || true)

  read -rp "Name [$defaultName] " name
  read -rp "Email [$defaultEmail] " email
  read -rp "Github username [$defaultGithub] " github

  git config -f ~/.gitconfig-local user.name "${name:-$defaultName}"
  git config -f ~/.gitconfig-local user.email "${email:-$defaultEmail}"
  git config -f ~/.gitconfig-local github.user "${github:-$defaultGithub}"

  if [[ "$(uname)" == "Darwin" ]]; then
    git config --global credential.helper "osxkeychain"
  else
    read -rn 1 -p "Save user and password to an unencrypted file to avoid writing? [y/N] " save
    if [[ $save =~ ^([Yy])$ ]]; then
      git config --global credential.helper "store"
    else
      git config --global credential.helper "cache --timeout 3600"
    fi
  fi
}

setup_homebrew() {
  title "Setting up Homebrew"

  if test ! "$(command -v brew)"; then
    info "Homebrew not installed. Installing."
    # Run as a login shell (non-interactive) so that the script doesn't pause for user input
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash --login
  fi

  if [ "$(uname)" == "Linux" ]; then
    test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
    test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
  fi

  # install brew dependencies from Brewfile
  brew bundle --file="$DOTFILES/Brewfile"

  # install fzf
  echo -e
  info "Installing fzf"
  "$(brew --prefix)"/opt/fzf/install --key-bindings --completion --no-update-rc --no-bash --no-fish
}

setup_shell() {
  title "Configuring shell"

  [[ -n "$(command -v brew)" ]] && zsh_path="$(brew --prefix)/bin/zsh" || zsh_path="$(command -v zsh)"
  if ! grep -qx "$zsh_path" /etc/shells; then
    info "adding $zsh_path to /etc/shells"
    echo "$zsh_path" | sudo tee -a /etc/shells
  fi

  if [[ "$SHELL" != "$zsh_path" ]]; then
    sudo chsh -s "$zsh_path" "$(whoami)"
    info "default shell changed to $zsh_path"
  fi

  local zinit_home="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"
  if [ ! -d "$zinit_home" ]; then
    info "Installing Zinit (first interactive shell start no longer has to do this over the network)"
    if ((DRY_RUN)); then
      info "[dry-run] git clone https://github.com/zdharma-continuum/zinit.git $zinit_home"
    else
      do_mkdir "$(dirname "$zinit_home")"
      git clone https://github.com/zdharma-continuum/zinit.git "$zinit_home"
    fi
  else
    info "Zinit already installed at $zinit_home... Skipping."
  fi
}

setup_macos() {
  title "Configuring macOS"
  if [[ "$(uname)" == "Darwin" ]]; then

    echo "Finder: show all filename extensions"
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true

    echo "show hidden files by default"
    defaults write com.apple.Finder AppleShowAllFiles -bool true

    echo "only use UTF-8 in Terminal.app"
    defaults write com.apple.terminal StringEncodings -array 4

    echo "expand save dialog by default"
    defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

    echo "show the ~/Library folder in Finder"
    chflags nohidden ~/Library

    echo "Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)"
    defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

    echo "Enable subpixel font rendering on non-Apple LCDs"
    defaults write NSGlobalDomain AppleFontSmoothing -int 2

    echo "Show Path bar in Finder"
    defaults write com.apple.finder ShowPathbar -bool true

    echo "Show Status bar in Finder"
    defaults write com.apple.finder ShowStatusBar -bool true

    echo "the default Finder view to list view"
    defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

    echo "default list view settings for new folders"
    defaults write com.apple.finder FK_StandardViewSettings -dict-add ListViewSettings '{ "columns" = ( { "ascending" = 1; "identifier" = "name"; "visible" = 1; "width" = 300; }, { "ascending" = 0; "identifier" = "dateModified"; "visible" = 1; "width" = 181; }, { "ascending" = 0; "identifier" = "size"; "visible" = 1; "width" = 97; } ); "iconSize" = 16; "showIconPreview" = 0; "sortColumn" = "name"; "textSize" = 12; "useRelativeDates" = 1; }'

    echo "existing folder view settings to force use of default settings"
    defaults delete com.apple.finder FXInfoPanesExpanded 2>/dev/null || true
    defaults delete com.apple.finder FXDesktopVolumePositions 2>/dev/null || true

    echo "Set list view for all view types"
    defaults write com.apple.finder FK_StandardViewSettings -dict-add ExtendedListViewSettings '{ "columns" = ( { "ascending" = 1; "identifier" = "name"; "visible" = 1; "width" = 300; }, { "ascending" = 0; "identifier" = "dateModified"; "visible" = 1; "width" = 181; }, { "ascending" = 0; "identifier" = "size"; "visible" = 1; "width" = 97; } ); "iconSize" = 16; "showIconPreview" = 0; "sortColumn" = "name"; "textSize" = 12; "useRelativeDates" = 1; }'

    echo "default search scope to the current folder"
    defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

    echo "trash items older than 30 days"
    defaults write com.apple.finder "FXRemoveOldTrashItems" -bool "true"

    echo "Remove .DS_Store files to reset folder view settings"
    find ~ -name ".DS_Store" -type f -delete 2>/dev/null || true

    echo "Show all filename extensions"
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true

    echo "Enable Safari’s debug menu"
    defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

    echo "Kill affected applications"

    # `|| true`: it's normal for some of these apps not to be running.
    for app in Safari Finder Dock Mail SystemUIServer; do killall "$app" >/dev/null 2>&1 || true; done
  else
    warning "macOS not detected. Skipping."
  fi
}

setup_hooks() {
  title "Installing git hooks"
  # core.hooksPath over symlinking into .git/hooks: one idempotent git-config
  # call, no per-hook symlink/chmod bookkeeping, and it keeps working from any
  # worktree of this repo (a worktree's .git is a file, not the hooks dir).
  if ((DRY_RUN)); then
    info "[dry-run] git -C \"$DOTFILES\" config core.hooksPath githooks"
  else
    git -C "$DOTFILES" config core.hooksPath githooks
  fi
  success "core.hooksPath set to githooks/ — githooks/pre-commit now runs on commit."
}

usage() {
  cat <<EOF

Usage: $(basename "$0") [--dry-run] [--non-interactive] <command>

Commands:
  backup           Back up existing dotfiles to ~/dotfiles-backup/
  clean            Remove symlinks created by link
  link             Create symlinks from config/ -> \$XDG_CONFIG_HOME, bin/ -> ~/bin, and
                   tracked config/{claude,codex,copilot} entries -> ~/.claude, ~/.codex, ~/.copilot
  copy             Copy configs instead of symlinking (useful for containers)
  codex-sync       Regenerate ~/.codex/config.toml from config.toml + config.local.toml
  skills           Link config/skills into every harness dir and ~/.claude/skills (also run by link)
  hooks            Install githooks/pre-commit via 'git config core.hooksPath'
  git              Set up Git identity and credential helper
  homebrew         Install Homebrew and run 'brew bundle' from the Brewfile
  shell            Set Zsh as the default shell and pre-install Zinit
  macos            Apply macOS system preferences
  all              Run link -> homebrew -> shell -> git -> macos
  help             Show this message

Flags:
  --dry-run         Print what would change without touching the filesystem
  --non-interactive Skip prompts (currently: the git identity prompts)

EOF
}

# ---------------------------------------------------------------------------
# Argument parsing: pull flags out of argv wherever they appear, leaving the
# first remaining word as the subcommand.
# ---------------------------------------------------------------------------
args=()
for arg in "$@"; do
  case "$arg" in
  --dry-run) DRY_RUN=1 ;;
  --non-interactive) NON_INTERACTIVE=1 ;;
  *) args+=("$arg") ;;
  esac
done

if ((DRY_RUN)); then
  info "--dry-run: no filesystem changes will be made"
fi

case "${args[0]:-}" in
backup)
  backup
  ;;
clean)
  cleanup_symlinks
  ;;
link)
  setup_symlinks
  fail_on_conflicts
  ;;
copy)
  copy
  ;;
codex-sync)
  codex_sync
  ;;
skills)
  setup_skills
  fail_on_conflicts
  ;;
hooks)
  setup_hooks
  ;;
git)
  setup_git
  ;;
homebrew)
  setup_homebrew
  ;;
shell)
  setup_shell
  ;;
macos)
  setup_macos
  ;;
all)
  setup_symlinks
  fail_on_conflicts
  setup_homebrew
  setup_shell
  setup_git
  setup_macos
  ;;
help | -h | --help)
  usage
  exit 0
  ;;
*)
  usage
  exit 1
  ;;
esac

echo -e
success "Done."
